version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: python tests/test.py
          name: Test
  lint:
    executor: python/default
    steps:
      - checkout
      - run:
          command: pip install pylint
          name: Install pylint
      - run:
          command: pylint serialclass
          name: Run pylint

  build-and-deploy:
    executor: python/default
    steps:
      - checkout
      - run:
          command: sed -i "s/dev/${CIRCLE_BUILD_NUM}/g" serialclass/__init__.py
          name: Update build number
      - run:
          command: python setup.py sdist bdist_wheel
          name: Create distribution archives
      - run:
          command: |
            pip install twine
            sed -i "s/pypi-token/${PYPI_SECRET}/g" .pypirc
            cp .pypirc $HOME/.pypirc
            twine upload --repository pypi dist/*


workflows:
  version: 2
  main:
    jobs:
      - test
      - lint
      - build-and-deploy:
          context: PYPI_UPLOAD
          requires:
            - test
            - lint
